// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID              uuid.UUID          `json:"id"`
	Url             string             `json:"url"`
	IntervalSeconds int32              `json:"intervalSeconds"`
	NextCheckAt     pgtype.Timestamptz `json:"nextCheckAt"`
	IsActive        bool               `json:"isActive"`
	UserID          uuid.UUID          `json:"userId"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

type UrlCheck struct {
	ID             uuid.UUID          `json:"id"`
	UrlID          uuid.UUID          `json:"urlId"`
	IsUp           bool               `json:"isUp"`
	StatusCode     int                `json:"statusCode"`
	ResponseTimeMs int64              `json:"responseTimeMs"`
	Error          *string            `json:"error"`
	CheckedAt      pgtype.Timestamptz `json:"checkedAt"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	Passwordhash string    `json:"passwordhash"`
}
