// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueURLs = `-- name: ClaimDueURLs :many
WITH due AS (
    SELECT id
    FROM urls
    WHERE is_active = true
      AND next_check_at <= NOW()
    ORDER BY next_check_at
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE urls u
SET next_check_at = NOW() + (u.interval_seconds * INTERVAL '1 second')
FROM due
WHERE u.id = due.id
RETURNING
    u.id,
    u.url,
    u.interval_seconds,
    u.next_check_at,
    u.is_active,
    u.user_id,
    u.created_at
`

func (q *Queries) ClaimDueURLs(ctx context.Context, limit int32) ([]Url, error) {
	rows, err := q.db.Query(ctx, claimDueURLs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.IntervalSeconds,
			&i.NextCheckAt,
			&i.IsActive,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createURL = `-- name: CreateURL :one
INSERT INTO urls (
    url,
    interval_seconds,
    user_id
)
VALUES (
    $1,
    $2,
    $3
) RETURNING id, url, interval_seconds
`

type CreateURLParams struct {
	Url             string    `json:"url"`
	IntervalSeconds int32     `json:"intervalSeconds"`
	UserID          uuid.UUID `json:"userId"`
}

type CreateURLRow struct {
	ID              uuid.UUID `json:"id"`
	Url             string    `json:"url"`
	IntervalSeconds int32     `json:"intervalSeconds"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (CreateURLRow, error) {
	row := q.db.QueryRow(ctx, createURL, arg.Url, arg.IntervalSeconds, arg.UserID)
	var i CreateURLRow
	err := row.Scan(&i.ID, &i.Url, &i.IntervalSeconds)
	return i, err
}

type CreateURLChecksParams struct {
	UrlID          uuid.UUID `json:"urlId"`
	IsUp           bool      `json:"isUp"`
	StatusCode     int       `json:"statusCode"`
	ResponseTimeMs int64     `json:"responseTimeMs"`
	Error          *string   `json:"error"`
}

const getURLByID = `-- name: GetURLByID :one
SELECT id, url, interval_seconds, next_check_at, is_active, user_id, created_at
FROM urls
WHERE id = $1 AND user_id = $2
`

type GetURLByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) GetURLByID(ctx context.Context, arg GetURLByIDParams) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByID, arg.ID, arg.UserID)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.IntervalSeconds,
		&i.NextCheckAt,
		&i.IsActive,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listURLChecksByURL = `-- name: ListURLChecksByURL :many
SELECT id, url_id, is_up, status_code, response_time_ms, error, checked_at
FROM url_checks
WHERE url_id = $1
ORDER BY checked_at DESC
LIMIT $2
`

type ListURLChecksByURLParams struct {
	UrlID uuid.UUID `json:"urlId"`
	Limit int32     `json:"limit"`
}

func (q *Queries) ListURLChecksByURL(ctx context.Context, arg ListURLChecksByURLParams) ([]UrlCheck, error) {
	rows, err := q.db.Query(ctx, listURLChecksByURL, arg.UrlID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UrlCheck
	for rows.Next() {
		var i UrlCheck
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.IsUp,
			&i.StatusCode,
			&i.ResponseTimeMs,
			&i.Error,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsByUser = `-- name: ListURLsByUser :many
SELECT id, url, interval_seconds, next_check_at, is_active, created_at FROM urls
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListURLsByUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Url             string             `json:"url"`
	IntervalSeconds int32              `json:"intervalSeconds"`
	NextCheckAt     pgtype.Timestamptz `json:"nextCheckAt"`
	IsActive        bool               `json:"isActive"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) ListURLsByUser(ctx context.Context, userID uuid.UUID) ([]ListURLsByUserRow, error) {
	rows, err := q.db.Query(ctx, listURLsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListURLsByUserRow
	for rows.Next() {
		var i ListURLsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.IntervalSeconds,
			&i.NextCheckAt,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateURLNextCheck = `-- name: UpdateURLNextCheck :exec
UPDATE urls
SET next_check_at = NOW() + (interval_seconds * INTERVAL '1 second')
WHERE id = $1
`

func (q *Queries) UpdateURLNextCheck(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateURLNextCheck, id)
	return err
}
