// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package repo

import (
	"context"
)

// iteratorForCreateURLChecks implements pgx.CopyFromSource.
type iteratorForCreateURLChecks struct {
	rows                 []CreateURLChecksParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateURLChecks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateURLChecks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UrlID,
		r.rows[0].IsUp,
		r.rows[0].StatusCode,
		r.rows[0].ResponseTimeMs,
		r.rows[0].Error,
	}, nil
}

func (r iteratorForCreateURLChecks) Err() error {
	return nil
}

func (q *Queries) CreateURLChecks(ctx context.Context, arg []CreateURLChecksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"url_checks"}, []string{"url_id", "is_up", "status_code", "response_time_ms", "error"}, &iteratorForCreateURLChecks{rows: arg})
}
