// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID              uuid.UUID
	Url             string
	IntervalSeconds int32
	NextCheckAt     pgtype.Timestamptz
	IsActive        bool
	UserID          uuid.UUID
	CreatedAt       pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	Username     string
	Passwordhash string
}
