// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	Actualurl pgtype.Text
	Shortcode pgtype.Text
	UserID    pgtype.UUID
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	Passwordhash string
}
