// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (
    url,
    interval_seconds,
    user_id
)
VALUES (
    $1,
    $2,
    $3
) RETURNING id, url, interval_seconds
`

type CreateURLParams struct {
	Url             string
	IntervalSeconds int32
	UserID          uuid.UUID
}

type CreateURLRow struct {
	ID              uuid.UUID
	Url             string
	IntervalSeconds int32
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (CreateURLRow, error) {
	row := q.db.QueryRow(ctx, createURL, arg.Url, arg.IntervalSeconds, arg.UserID)
	var i CreateURLRow
	err := row.Scan(&i.ID, &i.Url, &i.IntervalSeconds)
	return i, err
}

const listURLsByUser = `-- name: ListURLsByUser :many
SELECT url, interval_seconds FROM urls
WHERE user_id = $1
`

type ListURLsByUserRow struct {
	Url             string
	IntervalSeconds int32
}

func (q *Queries) ListURLsByUser(ctx context.Context, userID uuid.UUID) ([]ListURLsByUserRow, error) {
	rows, err := q.db.Query(ctx, listURLsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListURLsByUserRow
	for rows.Next() {
		var i ListURLsByUserRow
		if err := rows.Scan(&i.Url, &i.IntervalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
