// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (
    url,
    interval_seconds,
    user_id
)
VALUES (
    $1,
    $2,
    $3
) RETURNING id, url, interval_seconds
`

type CreateURLParams struct {
	Url             string
	IntervalSeconds int32
	UserID          uuid.UUID
}

type CreateURLRow struct {
	ID              uuid.UUID
	Url             string
	IntervalSeconds int32
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (CreateURLRow, error) {
	row := q.db.QueryRow(ctx, createURL, arg.Url, arg.IntervalSeconds, arg.UserID)
	var i CreateURLRow
	err := row.Scan(&i.ID, &i.Url, &i.IntervalSeconds)
	return i, err
}

const createURLCheck = `-- name: CreateURLCheck :one
INSERT INTO url_checks (
    url_id,
    is_up,
    status_code,
    response_time_ms,
    error
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, url_id, is_up, status_code, response_time_ms, error, checked_at
`

type CreateURLCheckParams struct {
	UrlID          uuid.UUID
	IsUp           bool
	StatusCode     int
	ResponseTimeMs int64
	Error          *string
}

func (q *Queries) CreateURLCheck(ctx context.Context, arg CreateURLCheckParams) (UrlCheck, error) {
	row := q.db.QueryRow(ctx, createURLCheck,
		arg.UrlID,
		arg.IsUp,
		arg.StatusCode,
		arg.ResponseTimeMs,
		arg.Error,
	)
	var i UrlCheck
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.IsUp,
		&i.StatusCode,
		&i.ResponseTimeMs,
		&i.Error,
		&i.CheckedAt,
	)
	return i, err
}

const getDueURLs = `-- name: GetDueURLs :many
SELECT
    id,
    url,
    interval_seconds,
    next_check_at,
    is_active,
    user_id,
    created_at
FROM urls
WHERE is_active = true
  AND next_check_at <= NOW()
ORDER BY next_check_at
LIMIT $1
`

func (q *Queries) GetDueURLs(ctx context.Context, limit int32) ([]Url, error) {
	rows, err := q.db.Query(ctx, getDueURLs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.IntervalSeconds,
			&i.NextCheckAt,
			&i.IsActive,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsByUser = `-- name: ListURLsByUser :many
SELECT url, interval_seconds FROM urls
WHERE user_id = $1
`

type ListURLsByUserRow struct {
	Url             string
	IntervalSeconds int32
}

func (q *Queries) ListURLsByUser(ctx context.Context, userID uuid.UUID) ([]ListURLsByUserRow, error) {
	rows, err := q.db.Query(ctx, listURLsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListURLsByUserRow
	for rows.Next() {
		var i ListURLsByUserRow
		if err := rows.Scan(&i.Url, &i.IntervalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateURLNextCheck = `-- name: UpdateURLNextCheck :exec
UPDATE urls
SET next_check_at = NOW() + (interval_seconds * INTERVAL '1 second')
WHERE id = $1
`

func (q *Queries) UpdateURLNextCheck(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateURLNextCheck, id)
	return err
}
