// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    passwordhash,
    username
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING email, username
`

type CreateUserParams struct {
	Email        string
	Passwordhash string
	Username     string
}

type CreateUserRow struct {
	Email    string
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Passwordhash, arg.Username)
	var i CreateUserRow
	err := row.Scan(&i.Email, &i.Username)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, passwordhash FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID
	Username     string
	Passwordhash string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Username, &i.Passwordhash)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID       pgtype.UUID
	Email    string
	Username string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}
