// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repo

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    passwordhash,
    username
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING email, username
`

type CreateUserParams struct {
	Email        string
	Passwordhash string
	Username     string
}

type CreateUserRow struct {
	Email    string
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Passwordhash, arg.Username)
	var i CreateUserRow
	err := row.Scan(&i.Email, &i.Username)
	return i, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT username, passwordhash FROM users
WHERE email = $1
`

type GetUserEmailRow struct {
	Username     string
	Passwordhash string
}

func (q *Queries) GetUserEmail(ctx context.Context, email string) (GetUserEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserEmail, email)
	var i GetUserEmailRow
	err := row.Scan(&i.Username, &i.Passwordhash)
	return i, err
}

const getUserUsername = `-- name: GetUserUsername :one
SELECT id, email, username, passwordhash FROM users
WHERE email = $1
AND passwordhash = $2
`

type GetUserUsernameParams struct {
	Email        string
	Passwordhash string
}

func (q *Queries) GetUserUsername(ctx context.Context, arg GetUserUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserUsername, arg.Email, arg.Passwordhash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Passwordhash,
	)
	return i, err
}
