### SignUp New User
POST http://localhost:3000/api/v1/signup
Content-Type: application/json

{
    "username": "theashgen1234",
    "email": "theashgen1234@gmail.com",
    "password": "theashgen@2402"
}

### Login
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email": "theashgen1234@gmail.com",
    "password": "theashgen@2402"
}

### GET URL
GET http://localhost:3000/api/v1/urls


### POST URL
POST http://localhost:3000/api/v1/urls
Content-Type: application/json

{
    "url": "ashwinsathiya.me",
    "interval": -120
}
